cabal-version:      3.0
name:               amc
version:            0.1.0.0
synopsis:           A multi-purpose advanced mathematical calculator
license:            MIT
license-file:       LICENSE
author:             Roman Maksimovich
maintainer:         r.a.maksimovich@gmail.com
category:           Math
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common common
    ghc-options: -Wall
    default-extensions:
        DataKinds
        GADTs
        StandaloneKindSignatures
        DefaultSignatures

library amclib
    import:           common
    hs-source-dirs:
        lib,
        -- lib/**/*
        -- lib/actions,
        -- -- lib/actions/spec,
        -- lib/object,
        -- lib/parse,
        -- lib/print,
        -- lib/spec
    exposed-modules:
        Object.Bundle,
        Object.RealNumber,
        Action.Bundle,
        Action.Simplify,
        Result,
        Description,
        Parse.Bundle,
        Parse.Instances.ParseIEX,
        Print.Bundle
    default-language: Haskell2010
    build-depends:
        base ^>=4.20.2.0

executable amc
    import:           common
    main-is:          Main.hs
    other-modules:    Input
    -- other-extensions:
    build-depends:
        base ^>=4.20.2.0,
        haskeline,
        amclib
    hs-source-dirs:   app
    default-language: Haskell2010
