cabal-version:      3.0
name:               amc
version:            0.1.0.0
synopsis:           A multi-purpose advanced mathematical calculator
license:            MIT
license-file:       LICENSE
author:             Roman Maksimovich
maintainer:         r.a.maksimovich@gmail.com
category:           Math
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library amclib
    import:           warnings
    hs-source-dirs:   lib
    exposed-modules:
        Object,
        RealNumber,
        Simplify,
        Action,
        Result,
        Description,
        Parse
    default-language: Haskell2010
    build-depends:
        base ^>=4.20.2.0

executable amc
    import:           warnings
    main-is:          Main.hs
    other-modules:    Action
    -- other-extensions:
    build-depends:
        base ^>=4.20.2.0,
        haskeline,
        amclib
    hs-source-dirs:   app
    default-language: Haskell2010
